### ISSUE TITLE
Mention 5 volt tolerance on your blog post and project page

### ISSUE THREAD

**Issue by drudru** [remy/ps2-remote#2]
Hi Remy, found your page on google.
Since I didn't see this covered here, you may want to put a note up about 5 volt tolerance.

The logic lines for the PS/2 keyboard and mouse are 5V TTL signals.
Luckily, the ESP8266 / Wemos D1 mini is *unofficially* 5 volt tolerant.
If it wasn't, you could have damaged the D1 mini.

**Comment by remy** [comment]
Yeah, that's actually a great point - I've got a similar device but I'm using the a raspberry pico as the main board, which … doesn't like 5v so much!
